spring:
  application:
    name: flowgoods
  flyway:
    enabled: true
    baseline-on-migrate: true
  mvc:
    problem-details:
      enabled: true
  config:
    import:
    - "classpath:errors/errors-user.yml"
    - "classpath:errors/errors-inventory.yml"
    - "classpath:errors/errors-jwt.yml"
    - "classpath:errors/errors-general.yml"
    - "classpath:errors/errors-password.yml"
    - "classpath:errors/errors-workspace.yml"
  jpa:
    show-sql: true

app:
  jwt:
    secret: 5eMC3WOWY2PVdKifPllqJqofpXr4RWHHTyDar4teXej
    expiration: 3600000
    type: "Bearer"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
