spring:
  application:
    name: flowgoods
  flyway:
    enabled: true
    baseline-on-migrate: true
  mvc:
    problem-details:
      enabled: true
  config:
    import:
    - "classpath:errors/errors-user.yml"
    - "classpath:errors/errors-inventory.yml"
    - "classpath:errors/errors-jwt.yml"
    - "classpath:errors/errors-general.yml"
    - "classpath:errors/errors-password.yml"
    - "classpath:errors/errors-workspace.yml"
    - "classpath:errors/error-finance.yml"
  jpa:
    show-sql: true

app:
  jwt:
    secret: ${JWT-SECRET:5eMC3WOWY2PVdKifPllqJqofpXr4RWHHTyDar4teXej}
    expiration: 3600000
    type: "Bearer"
  cursor:
    secret: ${CURSOR_SECRET_KEY:kaQ8u/I1nW+TCdHK51ayqABiIldKK3WWO5i1l2didKE=}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
